version: '3'
services:

  redis:
      image: redis:5.0.5-alpine
      command: 
        - redis-server /portfolio/app/redis/redis.conf
        - redis-server --appendonly yes
      container_name: db
      links:
        - rejson
      volumes:
        - ./server/redis:/portfolio/app/server/redis
      depends_on:
        - rejson
      ports:
        - "6379:6379"

  server:
    image:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/portfolio/app

  client:
    build: 
      dockerfile: DockerFile.dev
      context: ./client
    volumes:
      - ./client:/usr/app
      - /portfolio/app/client/node_modules
    links:
      - redis
    ports:
      - "8000:8000"
    depends_on:
      - redis